In [40]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\garov\.pyenv-win-venv\envs\bavforest\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\garov\.pyenv-win-venv\envs\bavforest\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
import pandas as pd
import numpy as np

In [42]:
file_path = r'C:\Users\garov\OneDrive\Desktop\DSSGx\Bavarian Forest Project\bavarian-forest-visitor-monitoring-dssgx-24-main\outputs\Raw Data\national-park-vacation-times-houses-opening-times.xlsx'

# Load the Excel file
df_visitcenters = pd.read_excel(file_path)

# Display the first few rows of the DataFrame
df_visitcenters.head()

,Datum,Wochentag,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,Parkpl_HEH_PKW,Parkpl_HEH_BUS,Parkpl_HZW_PKW,Parkpl_HZW_BUS,Schulferien_Bayern,...,Racheldiensthuette_geoeffnet,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max,Laubfärbung
0,2017-01-01,TTTT,571.0,872.0,55.0,469,1.0,156.0,0.0,1.0,...,0.0,0,1.0,1.0,0.2,0.0,12.0,59.86,345.0,0.0
1,2017-01-02,TTTT,241.0,527.0,90.0,184,1.0,87.0,0.0,1.0,...,0.0,0,1.0,1.0,-4.9,1.8,12.0,16.78,113.0,0.0
2,2017-01-03,TTTT,355.0,1237.0,53.0,246,2.0,115.0,0.0,1.0,...,0.0,0,1.0,1.0,-5.1,0.5,15.0,12.01,81.0,0.0
3,2017-01-04,TTTT,138.0,373.0,88.0,74,1.0,49.0,0.0,1.0,...,0.0,0,1.0,1.0,-4.1,13.3,30.0,11.71,83.0,0.0
4,2017-01-05,TTTT,281.0,406.0,24.0,179,4.0,55.0,0.0,1.0,...,0.0,0,1.0,1.0,-7.8,4.0,40.0,25.53,230.0,0.0

In [43]:
print(df_visitcenters.info)
print(df_visitcenters.columns)
print(df_visitcenters.describe())
print(df_visitcenters['Wochentag'].unique())

<bound method DataFrame.info of           Datum Wochentag  Besuchszahlen_HEH  Besuchszahlen_HZW  \
0    2017-01-01      TTTT              571.0              872.0
1    2017-01-02      TTTT              241.0              527.0
2    2017-01-03      TTTT              355.0             1237.0
3    2017-01-04      TTTT              138.0              373.0
4    2017-01-05      TTTT              281.0              406.0
...         ...       ...                ...                ...
2918 2024-12-28   Samstag                NaN                NaN
2919 2024-12-29   Sonntag                NaN                NaN
2920 2024-12-30    Montag                NaN                NaN
2921 2024-12-31  Dienstag                NaN                NaN
2922        NaT       NaN                NaN                NaN

      Besuchszahlen_WGM Parkpl_HEH_PKW  Parkpl_HEH_BUS  Parkpl_HZW_PKW  \
0                  55.0            469             1.0           156.0
1                  90.0            184             1.0            87.0
2                  53.0            246             2.0           115.0
3                  88.0             74             1.0            49.0
4                  24.0            179             4.0            55.0
...                 ...            ...             ...             ...
2918                NaN            NaN             NaN             NaN
2919                NaN            NaN             NaN             NaN
2920                NaN            NaN             NaN             NaN
2921                NaN            NaN             NaN             NaN
2922                NaN            NaN             NaN             NaN

      Parkpl_HZW_BUS  Schulferien_Bayern  ... Racheldiensthuette_geoeffnet  \
0                0.0                 1.0  ...                          0.0
1                0.0                 1.0  ...                          0.0
2                0.0                 1.0  ...                          0.0
3                0.0                 1.0  ...                          0.0
4                0.0                 1.0  ...                          0.0
...              ...                 ...  ...                          ...
2918             NaN                 1.0  ...                          NaN
2919             NaN                 1.0  ...                          NaN
2920             NaN                 1.0  ...                          NaN
2921             NaN                 1.0  ...                          NaN
2922             NaN                 NaN  ...                          NaN

      Waldschmidthaus_geoeffnet  Falkensteinschutzhaus_geoeffnet  \
0                             0                              1.0
1                             0                              1.0
2                             0                              1.0
3                             0                              1.0
4                             0                              1.0
...                         ...                              ...
2918                          0                              NaN
2919                          0                              NaN
2920                          0                              NaN
2921                          0                              NaN
2922                                                         NaN

      Schwellhaeusl_geoeffnet  Temperatur  Niederschlagsmenge  Schneehoehe  \
0                         1.0         0.2                 0.0         12.0
1                         1.0        -4.9                 1.8         12.0
2                         1.0        -5.1                 0.5         15.0
3                         1.0        -4.1                13.3         30.0
4                         1.0        -7.8                 4.0         40.0
...                       ...         ...                 ...          ...
2918                      NaN         NaN                 NaN          NaN
2919                      NaN         NaN                 NaN          NaN
2920                      NaN         NaN                 NaN          NaN
2921                      NaN         NaN                 NaN          NaN
2922                      NaN         NaN                 NaN          NaN

      GS mit GS max  Laubfärbung
0      59.86  345.0          0.0
1      16.78  113.0          0.0
2      12.01   81.0          0.0
3      11.71   83.0          0.0
4      25.53  230.0          0.0
...      ...    ...          ...
2918     NaN    NaN          NaN
2919     NaN    NaN          NaN
2920     NaN    NaN          NaN
2921     NaN    NaN          NaN
2922     NaN    NaN          NaN

[2923 rows x 27 columns]>
Index(['Datum', 'Wochentag', 'Besuchszahlen_HEH', 'Besuchszahlen_HZW',
       'Besuchszahlen_WGM', 'Parkpl_HEH_PKW', 'Parkpl_HEH_BUS',
       'Parkpl_HZW_PKW', 'Parkpl_HZW_BUS', 'Schulferien_Bayern',
       'Schulferien_CZ', 'Feiertag_Bayern', 'Feiertag_CZ', 'HEH_geoeffnet',
       'HZW_geoeffnet', 'WGM_geoeffnet', 'Lusenschutzhaus_geoeffnet',
       'Racheldiensthuette_geoeffnet', 'Waldschmidthaus_geoeffnet',
       'Falkensteinschutzhaus_geoeffnet', 'Schwellhaeusl_geoeffnet',
       'Temperatur', 'Niederschlagsmenge', 'Schneehoehe', 'GS mit', 'GS max',
       'Laubfärbung'],
      dtype='object')
                               Datum  Besuchszahlen_HEH  Besuchszahlen_HZW  \
count                           2922        2738.000000        2761.000000
mean   2020-12-31 06:00:14.784394240         395.135318         250.086201
min              2017-01-01 00:00:00           0.000000           0.000000
25%              2019-01-01 06:00:00         101.000000          82.000000
50%              2020-12-31 12:00:00         356.700000         229.000000
75%              2022-12-30 18:00:00         611.900000         375.000000
max              2024-12-31 00:00:00        1860.000000        2263.000000
std                              NaN         334.602471         210.103302

       Besuchszahlen_WGM  Parkpl_HEH_BUS  Parkpl_HZW_PKW  Parkpl_HZW_BUS  \
count        2769.000000     2741.000000     2749.000000     2749.000000
mean           38.864211        3.182780       52.594762        0.379411
min             0.000000        0.000000        0.000000        0.000000
25%             3.000000        0.000000        0.000000        0.000000
50%            26.000000        2.000000       46.000000        0.000000
75%            53.000000        5.000000       85.000000        0.000000
max           850.000000       22.000000      511.000000        8.000000
std            53.246913        3.377979       49.047309        0.917498

       Schulferien_Bayern  Feiertag_Bayern  Feiertag_CZ  ...  \
count         2922.000000      2922.000000  2922.000000  ...
mean             0.258385         0.037645     0.034223  ...
min              0.000000         0.000000     0.000000  ...
25%              0.000000         0.000000     0.000000  ...
50%              0.000000         0.000000     0.000000  ...
75%              1.000000         0.000000     0.000000  ...
max             10.000000         1.000000     1.000000  ...
std              0.471698         0.190370     0.181833  ...

       Lusenschutzhaus_geoeffnet  Racheldiensthuette_geoeffnet  \
count                2847.000000                   2852.000000
mean                    0.615385                      0.465288
min                     0.000000                      0.000000
25%                     0.000000                      0.000000
50%                     1.000000                      0.000000
75%                     1.000000                      1.000000
max                     1.000000                      1.000000
std                     0.486590                      0.498881

       Falkensteinschutzhaus_geoeffnet  Schwellhaeusl_geoeffnet   Temperatur  \
count                      2829.000000              2830.000000  2738.000000
mean                          0.622835                 0.786926     7.516420
min                           0.000000                 0.000000   -15.300000
25%                           0.000000                 1.000000     1.400000
50%                           1.000000                 1.000000     7.424306
75%                           1.000000                 1.000000    13.695139
max                           1.000000                 1.000000    25.200000
std                           0.484762                 0.409552     7.527411

       Niederschlagsmenge  Schneehoehe       GS mit       GS max  Laubfärbung
count         2738.000000  2729.000000  2738.000000  2736.000000  2799.000000
mean             3.211907     9.177721   122.959526   706.096923     0.020364
min             -2.400000     0.000000     0.000000     3.000000     0.000000
25%              0.000000     0.000000    44.440000   380.000000     0.000000
50%              0.200000     0.000000   102.845000   735.000000     0.000000
75%              3.775000     5.000000   192.031597  1026.000000     0.000000
max             66.800000   103.000000   357.131944  1496.000000     1.000000
std              6.195322    20.022333    90.038208   379.441640     0.141269

[8 rows x 23 columns]
['TTTT' 'Mittwoch' 'Donnerstag' 'Freitag' 'Samstag' 'Sonntag' 'Montag'
 'Dienstag' nan]

In [44]:
# Modify data types

# Make dummy coded variables instead on numeric (float64)
for column in df_visitcenters.columns:
    if df_visitcenters[column].isin([0, 1, np.nan]).all():  # Check if all values are 0, 1, or NaN
        df_visitcenters[column] = df_visitcenters[column].astype('bool')  # Convert to binary type

In [45]:
# Explore variable types
print(df_visitcenters.dtypes)

Datum                              datetime64[ns]
Wochentag                                  object
Besuchszahlen_HEH                         float64
Besuchszahlen_HZW                         float64
Besuchszahlen_WGM                         float64
Parkpl_HEH_PKW                             object
Parkpl_HEH_BUS                            float64
Parkpl_HZW_PKW                            float64
Parkpl_HZW_BUS                            float64
Schulferien_Bayern                        float64
Schulferien_CZ                             object
Feiertag_Bayern                              bool
Feiertag_CZ                                  bool
HEH_geoeffnet                                bool
HZW_geoeffnet                                bool
WGM_geoeffnet                             float64
Lusenschutzhaus_geoeffnet                    bool
Racheldiensthuette_geoeffnet                 bool
Waldschmidthaus_geoeffnet                  object
Falkensteinschutzhaus_geoeffnet              bool
Schwellhaeusl_geoeffnet                      bool
Temperatur                                float64
Niederschlagsmenge                        float64
Schneehoehe                               float64
GS mit                                    float64
GS max                                    float64
Laubfärbung                                  bool
dtype: object

In [46]:
# Convert object type variables to categorical
for col in df_visitcenters.select_dtypes(include=['object']).columns:
    df_visitcenters[col] = df_visitcenters[col].astype('category')

In [47]:
# Modify date variables to have separate variables for day, month, and year PICK UP HERE
df_visitcenters['Datum'] = pd.to_datetime(df_visitcenters['Datum'])

# Add separate columns for day, month, and year
df_visitcenters['Tag'] = df_visitcenters['Datum'].dt.day
df_visitcenters['Monat'] = df_visitcenters['Datum'].dt.month
df_visitcenters['Jahr'] = df_visitcenters['Datum'].dt.year

In [48]:
df_visitcenters.head()

,Datum,Wochentag,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,Parkpl_HEH_PKW,Parkpl_HEH_BUS,Parkpl_HZW_PKW,Parkpl_HZW_BUS,Schulferien_Bayern,...,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max,Laubfärbung,Tag,Monat,Jahr
0,2017-01-01,TTTT,571.0,872.0,55.0,469,1.0,156.0,0.0,1.0,...,True,0.2,0.0,12.0,59.86,345.0,False,1.0,1.0,2017.0
1,2017-01-02,TTTT,241.0,527.0,90.0,184,1.0,87.0,0.0,1.0,...,True,-4.9,1.8,12.0,16.78,113.0,False,2.0,1.0,2017.0
2,2017-01-03,TTTT,355.0,1237.0,53.0,246,2.0,115.0,0.0,1.0,...,True,-5.1,0.5,15.0,12.01,81.0,False,3.0,1.0,2017.0
3,2017-01-04,TTTT,138.0,373.0,88.0,74,1.0,49.0,0.0,1.0,...,True,-4.1,13.3,30.0,11.71,83.0,False,4.0,1.0,2017.0
4,2017-01-05,TTTT,281.0,406.0,24.0,179,4.0,55.0,0.0,1.0,...,True,-7.8,4.0,40.0,25.53,230.0,False,5.0,1.0,2017.0

In [49]:
df_visitcenters['Monat'] = df_visitcenters['Monat'].astype('category')

In [50]:
# Examine new date variables
print(df_visitcenters['Datum'].head())
print(df_visitcenters['Tag'].head())
print(df_visitcenters['Monat'].head())
print(df_visitcenters['Jahr'].head())
print(df_visitcenters.head())

0   2017-01-01
1   2017-01-02
2   2017-01-03
3   2017-01-04
4   2017-01-05
Name: Datum, dtype: datetime64[ns]
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
Name: Tag, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Monat, dtype: category
Categories (12, float64): [1.0, 2.0, 3.0, 4.0, ..., 9.0, 10.0, 11.0, 12.0]
0    2017.0
1    2017.0
2    2017.0
3    2017.0
4    2017.0
Name: Jahr, dtype: float64
       Datum Wochentag  Besuchszahlen_HEH  Besuchszahlen_HZW  \
0 2017-01-01      TTTT              571.0              872.0
1 2017-01-02      TTTT              241.0              527.0
2 2017-01-03      TTTT              355.0             1237.0
3 2017-01-04      TTTT              138.0              373.0
4 2017-01-05      TTTT              281.0              406.0

   Besuchszahlen_WGM Parkpl_HEH_PKW  Parkpl_HEH_BUS  Parkpl_HZW_PKW  \
0               55.0            469             1.0           156.0
1               90.0            184             1.0            87.0
2               53.0            246             2.0           115.0
3               88.0             74             1.0            49.0
4               24.0            179             4.0            55.0

   Parkpl_HZW_BUS  Schulferien_Bayern  ... Schwellhaeusl_geoeffnet  \
0             0.0                 1.0  ...                    True
1             0.0                 1.0  ...                    True
2             0.0                 1.0  ...                    True
3             0.0                 1.0  ...                    True
4             0.0                 1.0  ...                    True

   Temperatur  Niederschlagsmenge  Schneehoehe  GS mit  GS max  Laubfärbung  \
0         0.2                 0.0         12.0   59.86   345.0        False
1        -4.9                 1.8         12.0   16.78   113.0        False
2        -5.1                 0.5         15.0   12.01    81.0        False
3        -4.1                13.3         30.0   11.71    83.0        False
4        -7.8                 4.0         40.0   25.53   230.0        False

   Tag Monat    Jahr
0  1.0   1.0  2017.0
1  2.0   1.0  2017.0
2  3.0   1.0  2017.0
3  4.0   1.0  2017.0
4  5.0   1.0  2017.0

[5 rows x 30 columns]

In [51]:
df_visitcenters = df_visitcenters[['Datum', 'Tag', 'Monat', 'Jahr', 'Wochentag', 'Besuchszahlen_HEH', 'Besuchszahlen_HZW',
                      'Besuchszahlen_WGM', 'Parkpl_HEH_PKW', 'Parkpl_HEH_BUS',
                      'Parkpl_HZW_PKW', 'Parkpl_HZW_BUS', 'Schulferien_Bayern',
                      'Schulferien_CZ', 'Feiertag_Bayern', 'Feiertag_CZ', 'HEH_geoeffnet',
                      'HZW_geoeffnet', 'WGM_geoeffnet', 'Lusenschutzhaus_geoeffnet',
                      'Racheldiensthuette_geoeffnet', 'Waldschmidthaus_geoeffnet',
                      'Falkensteinschutzhaus_geoeffnet', 'Schwellhaeusl_geoeffnet',
                      'Temperatur', 'Niederschlagsmenge', 'Schneehoehe', 'GS mit', 'GS max',
                      'Laubfärbung']]

In [52]:
df_visitcenters['Tag'] = df_visitcenters['Tag'].astype('Int64')
df_visitcenters['Monat'] = df_visitcenters['Monat'].astype('Int64')
df_visitcenters['Monat'] = df_visitcenters['Monat'].astype('category')
df_visitcenters['Jahr'] = df_visitcenters['Jahr'].astype('Int64')
print(df_visitcenters.dtypes)

Datum                              datetime64[ns]
Tag                                         Int64
Monat                                    category
Jahr                                        Int64
Wochentag                                category
Besuchszahlen_HEH                         float64
Besuchszahlen_HZW                         float64
Besuchszahlen_WGM                         float64
Parkpl_HEH_PKW                           category
Parkpl_HEH_BUS                            float64
Parkpl_HZW_PKW                            float64
Parkpl_HZW_BUS                            float64
Schulferien_Bayern                        float64
Schulferien_CZ                           category
Feiertag_Bayern                              bool
Feiertag_CZ                                  bool
HEH_geoeffnet                                bool
HZW_geoeffnet                                bool
WGM_geoeffnet                             float64
Lusenschutzhaus_geoeffnet                    bool
Racheldiensthuette_geoeffnet                 bool
Waldschmidthaus_geoeffnet                category
Falkensteinschutzhaus_geoeffnet              bool
Schwellhaeusl_geoeffnet                      bool
Temperatur                                float64
Niederschlagsmenge                        float64
Schneehoehe                               float64
GS mit                                    float64
GS max                                    float64
Laubfärbung                                  bool
dtype: object

In [53]:
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,Parkpl_HEH_PKW,Parkpl_HEH_BUS,...,Racheldiensthuette_geoeffnet,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max,Laubfärbung
0,2017-01-01,1,1,2017,TTTT,571.0,872.0,55.0,469,1.0,...,False,0,True,True,0.2,0.0,12.0,59.86,345.0,False
1,2017-01-02,2,1,2017,TTTT,241.0,527.0,90.0,184,1.0,...,False,0,True,True,-4.9,1.8,12.0,16.78,113.0,False
2,2017-01-03,3,1,2017,TTTT,355.0,1237.0,53.0,246,2.0,...,False,0,True,True,-5.1,0.5,15.0,12.01,81.0,False
3,2017-01-04,4,1,2017,TTTT,138.0,373.0,88.0,74,1.0,...,False,0,True,True,-4.1,13.3,30.0,11.71,83.0,False
4,2017-01-05,5,1,2017,TTTT,281.0,406.0,24.0,179,4.0,...,False,0,True,True,-7.8,4.0,40.0,25.53,230.0,False

In [54]:
df_visitcenters['Jahreszeit'] = df_visitcenters['Monat'].apply(
    lambda x: 'Frühling' if x in [3, 4, 5] else
              'Sommer' if x in [6, 7, 8] else
              'Herbst' if x in [9, 10, 11] else
              'Winter' if x in [12, 1, 2] else
              NaN
)

In [55]:
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,Parkpl_HEH_PKW,Parkpl_HEH_BUS,...,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max,Laubfärbung,Jahreszeit
0,2017-01-01,1,1,2017,TTTT,571.0,872.0,55.0,469,1.0,...,0,True,True,0.2,0.0,12.0,59.86,345.0,False,Winter
1,2017-01-02,2,1,2017,TTTT,241.0,527.0,90.0,184,1.0,...,0,True,True,-4.9,1.8,12.0,16.78,113.0,False,Winter
2,2017-01-03,3,1,2017,TTTT,355.0,1237.0,53.0,246,2.0,...,0,True,True,-5.1,0.5,15.0,12.01,81.0,False,Winter
3,2017-01-04,4,1,2017,TTTT,138.0,373.0,88.0,74,1.0,...,0,True,True,-4.1,13.3,30.0,11.71,83.0,False,Winter
4,2017-01-05,5,1,2017,TTTT,281.0,406.0,24.0,179,4.0,...,0,True,True,-7.8,4.0,40.0,25.53,230.0,False,Winter

In [56]:
# Create a new column 'Day_of_Week' that shows the day of the week
df_visitcenters['Wochentag2'] = df_visitcenters['Datum'].dt.day_name()
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,Parkpl_HEH_PKW,Parkpl_HEH_BUS,...,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max,Laubfärbung,Jahreszeit,Wochentag2
0,2017-01-01,1,1,2017,TTTT,571.0,872.0,55.0,469,1.0,...,True,True,0.2,0.0,12.0,59.86,345.0,False,Winter,Sunday
1,2017-01-02,2,1,2017,TTTT,241.0,527.0,90.0,184,1.0,...,True,True,-4.9,1.8,12.0,16.78,113.0,False,Winter,Monday
2,2017-01-03,3,1,2017,TTTT,355.0,1237.0,53.0,246,2.0,...,True,True,-5.1,0.5,15.0,12.01,81.0,False,Winter,Tuesday
3,2017-01-04,4,1,2017,TTTT,138.0,373.0,88.0,74,1.0,...,True,True,-4.1,13.3,30.0,11.71,83.0,False,Winter,Wednesday
4,2017-01-05,5,1,2017,TTTT,281.0,406.0,24.0,179,4.0,...,True,True,-7.8,4.0,40.0,25.53,230.0,False,Winter,Thursday

In [57]:
print(df_visitcenters.dtypes)

Datum                              datetime64[ns]
Tag                                         Int64
Monat                                    category
Jahr                                        Int64
Wochentag                                category
Besuchszahlen_HEH                         float64
Besuchszahlen_HZW                         float64
Besuchszahlen_WGM                         float64
Parkpl_HEH_PKW                           category
Parkpl_HEH_BUS                            float64
Parkpl_HZW_PKW                            float64
Parkpl_HZW_BUS                            float64
Schulferien_Bayern                        float64
Schulferien_CZ                           category
Feiertag_Bayern                              bool
Feiertag_CZ                                  bool
HEH_geoeffnet                                bool
HZW_geoeffnet                                bool
WGM_geoeffnet                             float64
Lusenschutzhaus_geoeffnet                    bool
Racheldiensthuette_geoeffnet                 bool
Waldschmidthaus_geoeffnet                category
Falkensteinschutzhaus_geoeffnet              bool
Schwellhaeusl_geoeffnet                      bool
Temperatur                                float64
Niederschlagsmenge                        float64
Schneehoehe                               float64
GS mit                                    float64
GS max                                    float64
Laubfärbung                                  bool
Jahreszeit                                 object
Wochentag2                                 object
dtype: object

In [58]:
print(df_visitcenters.columns.values)

['Datum' 'Tag' 'Monat' 'Jahr' 'Wochentag' 'Besuchszahlen_HEH'
 'Besuchszahlen_HZW' 'Besuchszahlen_WGM' 'Parkpl_HEH_PKW' 'Parkpl_HEH_BUS'
 'Parkpl_HZW_PKW' 'Parkpl_HZW_BUS' 'Schulferien_Bayern' 'Schulferien_CZ'
 'Feiertag_Bayern' 'Feiertag_CZ' 'HEH_geoeffnet' 'HZW_geoeffnet'
 'WGM_geoeffnet' 'Lusenschutzhaus_geoeffnet'
 'Racheldiensthuette_geoeffnet' 'Waldschmidthaus_geoeffnet'
 'Falkensteinschutzhaus_geoeffnet' 'Schwellhaeusl_geoeffnet' 'Temperatur'
 'Niederschlagsmenge' 'Schneehoehe' 'GS mit' 'GS max' 'Laubfärbung'
 'Jahreszeit' 'Wochentag2']

In [59]:
df_visitcenters = df_visitcenters[['Datum', 'Tag', 'Monat', 'Jahr', 'Wochentag', 'Wochentag2', 'Laubfärbung',
                     'Jahreszeit', 'Besuchszahlen_HEH', 'Besuchszahlen_HZW', 'Besuchszahlen_WGM', 
                     'Parkpl_HEH_PKW', 'Parkpl_HEH_BUS', 'Parkpl_HZW_PKW', 'Parkpl_HZW_BUS', 
                     'Schulferien_Bayern', 'Schulferien_CZ', 'Feiertag_Bayern', 'Feiertag_CZ', 
                     'HEH_geoeffnet', 'HZW_geoeffnet', 'WGM_geoeffnet', 'Lusenschutzhaus_geoeffnet', 
                     'Racheldiensthuette_geoeffnet', 'Waldschmidthaus_geoeffnet', 
                     'Falkensteinschutzhaus_geoeffnet', 'Schwellhaeusl_geoeffnet', 'Temperatur', 
                     'Niederschlagsmenge', 'Schneehoehe', 'GS mit', 'GS max']]

In [60]:
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Wochentag2,Laubfärbung,Jahreszeit,Besuchszahlen_HEH,Besuchszahlen_HZW,...,Lusenschutzhaus_geoeffnet,Racheldiensthuette_geoeffnet,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max
0,2017-01-01,1,1,2017,TTTT,Sunday,False,Winter,571.0,872.0,...,True,False,0,True,True,0.2,0.0,12.0,59.86,345.0
1,2017-01-02,2,1,2017,TTTT,Monday,False,Winter,241.0,527.0,...,True,False,0,True,True,-4.9,1.8,12.0,16.78,113.0
2,2017-01-03,3,1,2017,TTTT,Tuesday,False,Winter,355.0,1237.0,...,True,False,0,True,True,-5.1,0.5,15.0,12.01,81.0
3,2017-01-04,4,1,2017,TTTT,Wednesday,False,Winter,138.0,373.0,...,True,False,0,True,True,-4.1,13.3,30.0,11.71,83.0
4,2017-01-05,5,1,2017,TTTT,Thursday,False,Winter,281.0,406.0,...,True,False,0,True,True,-7.8,4.0,40.0,25.53,230.0

In [61]:
df_visitcenters = df_visitcenters.apply(lambda x: x.astype(int) if x.dtype == 'bool' else x)

In [62]:
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Wochentag2,Laubfärbung,Jahreszeit,Besuchszahlen_HEH,Besuchszahlen_HZW,...,Lusenschutzhaus_geoeffnet,Racheldiensthuette_geoeffnet,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max
0,2017-01-01,1,1,2017,TTTT,Sunday,0,Winter,571.0,872.0,...,1,0,0,1,1,0.2,0.0,12.0,59.86,345.0
1,2017-01-02,2,1,2017,TTTT,Monday,0,Winter,241.0,527.0,...,1,0,0,1,1,-4.9,1.8,12.0,16.78,113.0
2,2017-01-03,3,1,2017,TTTT,Tuesday,0,Winter,355.0,1237.0,...,1,0,0,1,1,-5.1,0.5,15.0,12.01,81.0
3,2017-01-04,4,1,2017,TTTT,Wednesday,0,Winter,138.0,373.0,...,1,0,0,1,1,-4.1,13.3,30.0,11.71,83.0
4,2017-01-05,5,1,2017,TTTT,Thursday,0,Winter,281.0,406.0,...,1,0,0,1,1,-7.8,4.0,40.0,25.53,230.0

In [63]:
print(df_visitcenters.columns.values)

['Datum' 'Tag' 'Monat' 'Jahr' 'Wochentag' 'Wochentag2' 'Laubfärbung'
 'Jahreszeit' 'Besuchszahlen_HEH' 'Besuchszahlen_HZW' 'Besuchszahlen_WGM'
 'Parkpl_HEH_PKW' 'Parkpl_HEH_BUS' 'Parkpl_HZW_PKW' 'Parkpl_HZW_BUS'
 'Schulferien_Bayern' 'Schulferien_CZ' 'Feiertag_Bayern' 'Feiertag_CZ'
 'HEH_geoeffnet' 'HZW_geoeffnet' 'WGM_geoeffnet'
 'Lusenschutzhaus_geoeffnet' 'Racheldiensthuette_geoeffnet'
 'Waldschmidthaus_geoeffnet' 'Falkensteinschutzhaus_geoeffnet'
 'Schwellhaeusl_geoeffnet' 'Temperatur' 'Niederschlagsmenge' 'Schneehoehe'
 'GS mit' 'GS max']

In [64]:
# Define the translation mapping from English to German
translation_map = {
    'Monday': 'Montag',
    'Tuesday': 'Dienstag',
    'Wednesday': 'Mittwoch',
    'Thursday': 'Donnerstag',
    'Friday': 'Freitag',
    'Saturday': 'Samstag',
    'Sunday': 'Sonntag'
}

# Replace the English day names in the 'Wochentag2' column with German names
df_visitcenters['Wochentag2'] = df_visitcenters['Wochentag2'].replace(translation_map)

# Remove the 'Wochentag' column from the DataFrame
df_visitcenters = df_visitcenters.drop(columns=['Wochentag'])

# Rename 'Wochentag2' to 'Wochentag'
df_visitcenters = df_visitcenters.rename(columns={'Wochentag2': 'Wochentag'})

In [65]:
df_visitcenters.head()

,Datum,Tag,Monat,Jahr,Wochentag,Laubfärbung,Jahreszeit,Besuchszahlen_HEH,Besuchszahlen_HZW,Besuchszahlen_WGM,...,Lusenschutzhaus_geoeffnet,Racheldiensthuette_geoeffnet,Waldschmidthaus_geoeffnet,Falkensteinschutzhaus_geoeffnet,Schwellhaeusl_geoeffnet,Temperatur,Niederschlagsmenge,Schneehoehe,GS mit,GS max
0,2017-01-01,1,1,2017,Sonntag,0,Winter,571.0,872.0,55.0,...,1,0,0,1,1,0.2,0.0,12.0,59.86,345.0
1,2017-01-02,2,1,2017,Montag,0,Winter,241.0,527.0,90.0,...,1,0,0,1,1,-4.9,1.8,12.0,16.78,113.0
2,2017-01-03,3,1,2017,Dienstag,0,Winter,355.0,1237.0,53.0,...,1,0,0,1,1,-5.1,0.5,15.0,12.01,81.0
3,2017-01-04,4,1,2017,Mittwoch,0,Winter,138.0,373.0,88.0,...,1,0,0,1,1,-4.1,13.3,30.0,11.71,83.0
4,2017-01-05,5,1,2017,Donnerstag,0,Winter,281.0,406.0,24.0,...,1,0,0,1,1,-7.8,4.0,40.0,25.53,230.0

In [66]:
# Specify the path where you want to save the CSV file
file_path = r'C:\Users\garov\OneDrive\Desktop\DSSGx\Bavarian Forest Project\bavarian-forest-visitor-monitoring-dssgx-24-main\outputs\Cleaned Data\df_visitcenters.csv'

# Export the DataFrame to a CSV file
df_visitcenters.to_csv(file_path, index=False)