# Sourcing Weather Data

In [2]:
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Point, Hourly
from meteostat import Stations

## Load historical weather data for a given time period

In [5]:
def get_stations_nearby(lat, lon):

    """
    Get the nearby weather stations for the given latitude and longitude

    Parameters:
    ----------  
    lat : float
        Latitude of the location
    lon : float
        Longitude of the location

    Returns:
    -------
    stations : list
        List of nearby weather stations

    """
    # Get nearby weather stations
    stations = Stations()

    # Get the German weather stations
    stations = stations.region('DE')

    # Get the nearby stations for the given latitide and longitude
    stations = stations.nearby(lat,lon)

    # Fetch 1 station
    count = stations.region('DE').count()
    stations = stations.fetch(5, sample=True)

    return stations, count

In [ ]:
def get_hourly_weather_data(station, start_time, end_time):
    # Set time period
    start

In [4]:
# Set time period
start_time = datetime(2017, 1, 1)
end_time = datetime(2024, 7, 31)

lat = 48.9945849
lon = 13.379928136136467

# Create Point for Vancouver, BC
bavarian_forest = Point(lat,lon, 1088)

# Get nearby weather stations
stations,count = get_stations_nearby(lat, lon)


# stations.head()
print(type(start_time))

<class 'datetime.datetime'>

In [29]:






# Get daily data for the time period
data = Hourly(bavarian_forest, start, end)
data = data.fetch()
# See about the dataframe columns here : https://dev.meteostat.net/python/daily.html#data-structure
data.head()

1262

,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end,distance
id,,,,,,,,,,,,,,,,
10805,Lahr,DE,BW,10805,EDTL,48.3667,7.8333,155.0,Europe/Berlin,1973-01-01,2024-08-12,1950-01-01,2024-08-10,1950-01-01,2022-01-01,413060.658131
D6258,Friedrichshafen-Unterraderach,DE,BW,<NA>,<NA>,47.6845,9.4409,459.0,Europe/Berlin,2003-01-01,2024-08-10,2003-01-01,2024-08-10,2003-01-01,2022-01-01,325500.054317
D3308,Mittenwalde/Uckermark,DE,BB,<NA>,<NA>,53.1846,13.6546,72.0,Europe/Berlin,2005-08-01,2024-08-10,2005-08-02,2022-04-25,2005-01-01,2021-01-01,466302.208307
D5382,Wedemark-Elze,DE,NI,<NA>,<NA>,52.5883,9.7386,39.0,Europe/Berlin,2006-05-01,2024-08-10,2006-05-02,2022-04-25,2006-01-01,2022-01-01,474408.315885
7U878,Wertingen,DE,BY,<NA>,<NA>,48.5700,10.6985,420.0,Europe/Berlin,2022-07-09,2024-01-09,NaT,NaT,NaT,NaT,202045.968117

In [ ]:
# Plot line chart including average, minimum and maximum temperature
data.plot(y=['tavg', 'tmin', 'tmax'])
plt.show()